[pytest]
testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -v
    --headed
    --browser chromium
    --tb=short
    --html=Reports/HTML/report.html
    --self-contained-html

markers =
    smoke: Critical tests that verify the application is working
    regression: Full regression test suite
    authentication: Authentication tests
    navigation: Navigation tests
    inventory: Inventory page tests
    cart: Shopping cart tests
    checkout: Checkout tests
    menu: Burger menu tests
    links: External links tests